from pony.orm import *
from db.models import *
from db.cartas_session import *

CARTAS_POR_JUGADOR = {
    4 : {
        'Infectado':8,
		'Lanzallamas':2,
		'Carta Vacia':4,
        'Sospecha':4,
        'Seduccion':2,
        'Mas vale que corras':2,
        'Cambio de lugar':2,
        'Analisis':0,
        'Whisky':1,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':2,
        'La cosa':1,
	},
    5 : {
		'Infectado':8,
		'Lanzallamas':2,
		'Carta Vacia':9,
        'Sospecha':4,
        'Seduccion':2,
        'Mas vale que corras':2,
        'Cambio de lugar':2,
        'Analisis':1,
        'Whisky':1,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':2,
        'La cosa':1,
    },
    6 : {'Infectado':10,
		'Lanzallamas':3,
		'Carta Vacia':16,
        'Sospecha':4,
        'Seduccion':3,
        'Mas vale que corras':2,
        'Cambio de lugar':2,
        'Analisis':2,
        'Whisky':2,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':3,
        'La cosa':1,
    },
    7 : {'Infectado':12,
		'Lanzallamas':3,
		'Carta Vacia':19,
        'Sospecha':5,
        'Seduccion':4,
        'Mas vale que corras':3,
        'Cambio de lugar':3,
        'Analisis':2,
        'Whisky':2,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':3,
        'La cosa':1,
    },
    8 : {'Infectado':13,
		'Lanzallamas':3,
		'Carta Vacia':23,
        'Sospecha':6,
        'Seduccion':5,
        'Mas vale que corras':3,
        'Cambio de lugar':3,
        'Analisis':2,
        'Whisky':2,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':3,
        'La cosa':1,
    },
    9: {'Infectado':15,
		'Lanzallamas':4,
		'Carta Vacia':31,
        'Sospecha':7,
        'Seduccion':5,
        'Mas vale que corras':4,
        'Cambio de lugar':4,
        'Analisis':3,
        'Whisky':2,
        'Hacha':2,
        'Vigila tus espaldas':2,
        'Determinacion':4,
        'La cosa':1,
    },
    10: {'Infectado':17,
		'Lanzallamas':4,
		'Carta Vacia':33,
        'Sospecha':8,
        'Seduccion':6,
        'Mas vale que corras':4,
        'Cambio de lugar':4,
        'Analisis':3,
        'Whisky':3,
        'Hacha':2,
        'Vigila tus espaldas':2,
        'Determinacion':5,
        'La cosa':1,
    },
    11: {'Infectado':20,
		'Lanzallamas':5,
		'Carta Vacia':39,
        'Sospecha':8,
        'Seduccion':7,
        'Mas vale que corras':5,
        'Cambio de lugar':5,
        'Analisis':3,
        'Whisky':3,
        'Hacha':2,
        'Vigila tus espaldas':2,
        'Determinacion':5,
        'La cosa':1,
    },
    12: {'Infectado':20,
		'Lanzallamas':5,
		'Carta Vacia':39,
        'Sospecha':8,
        'Seduccion':7,
        'Mas vale que corras':5,
        'Cambio de lugar':5,
        'Analisis':3,
        'Whisky':3,
        'Hacha':2,
        'Vigila tus espaldas':2,
        'Determinacion':5,
        'La cosa':1,
    }
}


@db_session
def crear_mazo_jugadores(partida, cantidad_jug):
    for nombres in TemplateCarta.select():
        for _ in range(CARTAS_POR_JUGADOR[cantidad_jug][nombres.nombre]):
            crear_carta(TemplateCarta.get(nombre=nombres.nombre),partida)
    return 0

def crear_mazo(partida):
    num_jugadores = len(partida.jugadores)
    crear_mazo_jugadores(partida,num_jugadores)
    return 0    
        