from pony.orm import *
from db.models import *
from db.cartas_session import *

CARTAS_POR_JUGADOR = {
    4 : {
        'Infectado':8,
		'Lanzallamas':2,
        'Sospecha':4,
        'Seduccion':2,
        'Mas vale que corras':2,
        'Cambio de lugar':2,
        'Analisis':0,
        'Whisky':1,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':2,
        'La cosa':1,
        'Aterrador':0,
        'Aqui estoy bien':1,
        'No, gracias':1,
        'Fallaste':1,
        'Nada de barbacoas':1,
        'Puerta atrancada':1,
        'Cuarentena':0,
        'Revelaciones':0,
        'Sal de aqui':0,
        'Olvidadizo':1,
        'Cuerdas podridas':0,
        'Uno, dos':0,
        'Tres, cuatro':1,
        'Es aqui la fiesta?':0,
        'Que quede entre nosotros':0,
        'Vuelta y vuelta':1,
        'No podemos ser amigos?':0,
        'Cita a ciegas':1,
        'Ups':0,
	},
    5 : {
		'Infectado':8,
		'Lanzallamas':2,
        'Sospecha':4,
        'Seduccion':2,
        'Mas vale que corras':2,
        'Cambio de lugar':2,
        'Analisis':1,
        'Whisky':1,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':2,
        'La cosa':1,
        'Aterrador':1,
        'Aqui estoy bien':1,
        'No, gracias':1,
        'Fallaste':1,
        'Nada de barbacoas':1,
        'Puerta atrancada':1,
        'Cuarentena':1,
        'Revelaciones':0,
        'Sal de aqui':1,
        'Olvidadizo':1,
        'Cuerdas podridas':0,
        'Uno, dos':1,
        'Tres, cuatro':1,
        'Es aqui la fiesta?':1,
        'Que quede entre nosotros':0,
        'Vuelta y vuelta':1,
        'No podemos ser amigos?':0,
        'Cita a ciegas':1,
        'Ups':0,
    },
    6 : {'Infectado':10,
		'Lanzallamas':3,
        'Sospecha':4,
        'Seduccion':3,
        'Mas vale que corras':2,
        'Cambio de lugar':2,
        'Analisis':2,
        'Whisky':2,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':3,
        'La cosa':1,
        'Aterrador':2,
        'Aqui estoy bien':2,
        'No, gracias':2,
        'Fallaste':2,
        'Nada de barbacoas':2,
        'Puerta atrancada':1,
        'Cuarentena':1,
        'Revelaciones':0,
        'Sal de aqui':1,
        'Olvidadizo':1,
        'Cuerdas podridas':1,
        'Uno, dos':1,
        'Tres, cuatro':1,
        'Es aqui la fiesta?':1,
        'Que quede entre nosotros':0,
        'Vuelta y vuelta':1,
        'No podemos ser amigos?':0,
        'Cita a ciegas':1,
        'Ups':0,
    },
    7 : {'Infectado':12,
		'Lanzallamas':3,
        'Sospecha':5,
        'Seduccion':4,
        'Mas vale que corras':3,
        'Cambio de lugar':3,
        'Analisis':2,
        'Whisky':2,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':3,
        'La cosa':1,
        'Aterrador':2,
        'Aqui estoy bien':2,
        'No, gracias':2,
        'Fallaste':2,
        'Nada de barbacoas':2,
        'Puerta atrancada':2,
        'Cuarentena':1,
        'Revelaciones':0,
        'Sal de aqui':1,
        'Olvidadizo':1,
        'Cuerdas podridas':1,
        'Uno, dos':1,
        'Tres, cuatro':1,
        'Es aqui la fiesta?':1,
        'Que quede entre nosotros':1,
        'Vuelta y vuelta':1,
        'No podemos ser amigos?':1,
        'Cita a ciegas':1,
        'Ups':0,
    },
    8 : {'Infectado':13,
		'Lanzallamas':3,
        'Sospecha':6,
        'Seduccion':5,
        'Mas vale que corras':3,
        'Cambio de lugar':3,
        'Analisis':2,
        'Whisky':2,
        'Hacha':1,
        'Vigila tus espaldas':1,
        'Determinacion':3,
        'La cosa':1,
        'Aterrador':3,
        'Aqui estoy bien':2,
        'No, gracias':3,
        'Fallaste':2,
        'Nada de barbacoas':2,
        'Puerta atrancada':2,
        'Cuarentena':1,
        'Revelaciones':1,
        'Sal de aqui':1,
        'Olvidadizo':1,
        'Cuerdas podridas':1,
        'Uno, dos':1,
        'Tres, cuatro':1,
        'Es aqui la fiesta?':1,
        'Que quede entre nosotros':1,
        'Vuelta y vuelta':1,
        'No podemos ser amigos?':1,
        'Cita a ciegas':1,
        'Ups':0,
    },
    9: {'Infectado':15,
		'Lanzallamas':4,
        'Sospecha':7,
        'Seduccion':5,
        'Mas vale que corras':4,
        'Cambio de lugar':4,
        'Analisis':3,
        'Whisky':2,
        'Hacha':2,
        'Vigila tus espaldas':2,
        'Determinacion':4,
        'La cosa':1,
        'Aterrador':3,
        'Aqui estoy bien':2,
        'No, gracias':3,
        'Fallaste':2,
        'Nada de barbacoas':2,
        'Puerta atrancada':2,
        'Cuarentena':2,
        'Revelaciones':1,
        'Sal de aqui':1,
        'Olvidadizo':1,
        'Cuerdas podridas':2,
        'Uno, dos':2,
        'Tres, cuatro':2,
        'Es aqui la fiesta?':2,
        'Que quede entre nosotros':2,
        'Vuelta y vuelta':2,
        'No podemos ser amigos?':2,
        'Cita a ciegas':2,
        'Ups':0,
    },
    10: {'Infectado':17,
		'Lanzallamas':4,
        'Sospecha':8,
        'Seduccion':6,
        'Mas vale que corras':4,
        'Cambio de lugar':4,
        'Analisis':3,
        'Whisky':3,
        'Hacha':2,
        'Vigila tus espaldas':2,
        'Determinacion':5,
        'La cosa':1,
        'Aterrador':3,
        'Aqui estoy bien':2,
        'No, gracias':3,
        'Fallaste':2,
        'Nada de barbacoas':2,
        'Puerta atrancada':2,
        'Cuarentena':2,
        'Revelaciones':1,
        'Sal de aqui':1,
        'Olvidadizo':1,
        'Cuerdas podridas':2,
        'Uno, dos':2,
        'Tres, cuatro':2,
        'Es aqui la fiesta?':2,
        'Que quede entre nosotros':2,
        'Vuelta y vuelta':2,
        'No podemos ser amigos?':2,
        'Cita a ciegas':2,
        'Ups':1,
    },
    11: {'Infectado':20,
		'Lanzallamas':5,
        'Sospecha':8,
        'Seduccion':7,
        'Mas vale que corras':5,
        'Cambio de lugar':5,
        'Analisis':3,
        'Whisky':3,
        'Hacha':2,
        'Vigila tus espaldas':2,
        'Determinacion':5,
        'La cosa':1,
        'Aterrador':4,
        'Aqui estoy bien':3, 
        'No, gracias':4,
        'Fallaste':3,
        'Nada de barbacoas':3,
        'Puerta atrancada':3,
        'Cuarentena':2,
        'Revelaciones':1,
        'Sal de aqui':1,
        'Olvidadizo':1,
        'Cuerdas podridas':2,
        'Uno, dos':2,
        'Tres, cuatro':2,
        'Es aqui la fiesta?':2,
        'Que quede entre nosotros':2,
        'Vuelta y vuelta':2,
        'No podemos ser amigos?':2,
        'Cita a ciegas':2,
        'Ups':1,
    },
    12: {'Infectado':20,
		'Lanzallamas':5,
        'Sospecha':8,
        'Seduccion':7,
        'Mas vale que corras':5,
        'Cambio de lugar':5,
        'Analisis':3,
        'Whisky':3,
        'Hacha':2,
        'Vigila tus espaldas':2,
        'Determinacion':5,
        'La cosa':1,
        'Aterrador':4,
        'Aqui estoy bien':3, 
        'No, gracias':4,
        'Fallaste':3,
        'Nada de barbacoas':3,
        'Puerta atrancada':3,
        'Cuarentena':2,
        'Revelaciones':1,
        'Sal de aqui':1,
        'Olvidadizo':1,
        'Cuerdas podridas':2,
        'Uno, dos':2,
        'Tres, cuatro':2,
        'Es aqui la fiesta?':2,
        'Que quede entre nosotros':2,
        'Vuelta y vuelta':2,
        'No podemos ser amigos?':2,
        'Cita a ciegas':2,
        'Ups':1,
    }
}


@db_session
def crear_mazo_jugadores(partida, cantidad_jug):
    for nombres in TemplateCarta.select():
        for _ in range(CARTAS_POR_JUGADOR[cantidad_jug][nombres.nombre]):
            crear_carta(TemplateCarta.get(nombre=nombres.nombre),partida)
    return 0

def crear_mazo(partida):
    num_jugadores = len(partida.jugadores)
    crear_mazo_jugadores(partida,num_jugadores)
    return 0    
        